### ISSUE TITLE
Can I highlight the type of $type(fix/feat/xxx) in the submit window?

### ISSUE THREAD

**Issue by ZHOUXING1997** [EugeneKozhun/commit-message-template#18]

**Comment by EugeneKozhun** [comment]
No, you can't. The message field has its own syntax with auto-completion by default (but without highlighting).

This is not the purpose of this plugin at the moment. Syntax highlighting is planned only for the template in the settings.

**Comment by ZHOUXING1997** [comment]
![image](https://github.com/EugeneKozhun/commit-message-template/assets/33240857/76560c53-7afb-4e40-bc3a-f66cb08cad6d)

It's just only show

**Comment by EugeneKozhun** [comment]
Maybe in future releases :)
